### ISSUE TITLE
footer not visible

### ISSUE THREAD

**Issue by Howuhh** [andyzeng/andyzeng.github.io#1]
Hi! Very beautiful site and template! Love it. 

But, in all browsers that I have tried, I cannot see the footer text. I think the problem is in footer position set to the absolute. 
https://github.com/andyzeng/andyzeng.github.io/blob/c382af544e861f1de12c9bff7361f8ccc7d8b583/style.css#L309

Relative position fixes everything for me.

**Comment by andyzeng** [comment]
Thanks for the catch!
I meant to have the footer stick to the bottom of the page, but indeed it wasn't quite right the first time around. Dropped in a fix in the latest commit.

Cheers,
